# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sega/tetris/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sega/tetris/proprietary/etc/cert/sega.cer:system/etc/cert/sega.cer \
    vendor/sega/tetris/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/sega/tetris/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/sega/tetris/proprietary/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \
    vendor/sega/tetris/proprietary/etc/firmware/BCM4330B1_002.001.003.0550.0000_TESTONLY_LGE_X3.hcd:system/etc/firmware/BCM4330B1_002.001.003.0550.0000_TESTONLY_LGE_X3.hcd \
    vendor/sega/tetris/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/sega/tetris/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/sega/tetris/proprietary/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/sega/tetris/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/sega/tetris/proprietary/vendor/lib/libtiutils.so:system/vendor/lib/libtiutils.so \
    vendor/sega/tetris/proprietary/vendor/lib/libtinyalsa.so:system/vendor/lib/libtinyalsa.so \
    vendor/sega/tetris/proprietary/vendor/lib/libIMGegl_SGX540_120.so:system/vendor/lib/libIMGegl_SGX540_120.so \
    vendor/sega/tetris/proprietary/vendor/bin/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/sega/tetris/proprietary/bin/sensord:system/bin/sensord \
    vendor/sega/tetris/proprietary/bin/glgps:system/bin/glgps \
    vendor/sega/tetris/proprietary/bin/rild:system/bin/rild \